import type { BlogLocale } from "@/lib/blog-routing";

type BlogCopy = {
  eyebrow: string;
  indexTitle: string;
  indexDescription: string;
  policyNotice: string;
  indexSeoTitle: string;
  indexSeoDescription: string;
  emptyTitle: string;
  emptyDescription: string;
  readArticle: string;
  updated: string;
  published: string;
  minutes: string;
  reviewBadge: string;
  home: string;
  indexName: string;
  asOf: string;
  jurisdiction: string;
  author: string;
  reviewer: string;
  reviewedAt: string;
  sourcesTitle: string;
  sourcesDescription: string;
  accessedAt: string;
  effectiveAt: string;
  relatedTitle: string;
  backToIndex: string;
  disclosureTitle: string;
  aiDisclosure: string;
  humanDisclosure: string;
  legalNotice: string;
  revisions: string;
  contactTitle: string;
  contactDescription: string;
  contactCta: string;
  latestTitle: string;
  latestDescription: string;
  latestCta: string;
  processLabel: string;
};

export const BLOG_COPY: Record<BlogLocale, BlogCopy> = {
  ko: {
    eyebrow: "INSIGHTS",
    indexTitle: "외국인력 채용을 위한 기준 있는 실무 가이드",
    indexDescription: "비자 이름만 나열하지 않습니다. 기업이 실제로 결정해야 하는 직무, 계약, 입국, 정착의 순서와 공식 확인 경로를 정리합니다.",
    policyNotice: "제도와 기준은 변동될 수 있습니다. 각 글의 기준일, 수정일, 공식 출처를 확인하고 실제 신청 전에는 관할 기관의 최신 안내를 검토하세요.",
    indexSeoTitle: "인사이트 | 외국인력 채용·비자 가이드",
    indexSeoDescription: "외국인력 채용, 한국 취업비자, 일본 특정기능 채용에 관한 기업 실무 가이드입니다. 공식 출처와 기준일을 함께 안내합니다.",
    emptyTitle: "검토를 마친 글을 준비하고 있습니다",
    emptyDescription: "공식 출처와 시행일을 확인한 글만 이 목록에 게시합니다.",
    readArticle: "글 읽기",
    updated: "수정일",
    published: "게시일",
    minutes: "분",
    reviewBadge: "검토 중",
    home: "홈",
    indexName: "인사이트",
    asOf: "기준일",
    jurisdiction: "관할",
    author: "작성",
    reviewer: "검토",
    reviewedAt: "검토일",
    sourcesTitle: "공식 출처",
    sourcesDescription: "핵심 사실은 아래 1차 출처를 기준으로 확인했습니다.",
    accessedAt: "확인일",
    effectiveAt: "시행일",
    relatedTitle: "함께 확인할 내용",
    backToIndex: "모든 인사이트 보기",
    disclosureTitle: "작성·검토 정보",
    aiDisclosure: "이 글은 AI의 초안·정리 보조를 받았으며, 표시된 공식 1차 출처와 핵심 사실을 대조했습니다. 별도의 사람 검토자를 표기하지 않습니다.",
    humanDisclosure: "이 글은 공식 1차 출처와 핵심 사실을 대조해 작성했습니다. 별도의 사람 검토자는 실제 검토가 있을 때만 표기합니다.",
    legalNotice: "이 글은 일반적인 정보 제공을 위한 것으로, 개별 사안에 대한 법률·노무·행정 자문이 아닙니다.",
    revisions: "게시 및 수정 이력",
    contactTitle: "기업의 채용 요건을 함께 정리해 보세요.",
    contactDescription: "교육, 매칭, 비자, 정착까지 필요한 단계와 역할을 안내합니다.",
    contactCta: "채용 준비 안내",
    latestTitle: "최근 인사이트",
    latestDescription: "공식 출처를 바탕으로 채용과 비자 제도의 핵심을 실무 관점에서 정리합니다.",
    latestCta: "전체 글 보기",
    processLabel: "이 글의 확인 순서",
  },
  en: {
    eyebrow: "INSIGHTS",
    indexTitle: "Evidence-based guides for international hiring",
    indexDescription: "Practical sequences for roles, contracts, entry procedures and settlement support, with links to the responsible authorities.",
    policyNotice: "Rules can change. Check each article's as-of date, update date and official sources before making an application.",
    indexSeoTitle: "Insights | Foreign worker hiring and visa guides",
    indexSeoDescription: "Practical employer guides to Korean work visas and Japan's Specified Skilled Worker system, with official sources and dates.",
    emptyTitle: "Verified articles are being prepared",
    emptyDescription: "Only articles cross-checked against official sources are published here.",
    readArticle: "Read article",
    updated: "Updated",
    published: "Published",
    minutes: " min",
    reviewBadge: "Under review",
    home: "Home",
    indexName: "Insights",
    asOf: "As of",
    jurisdiction: "Jurisdiction",
    author: "Author",
    reviewer: "Reviewer",
    reviewedAt: "Reviewed",
    sourcesTitle: "Official sources",
    sourcesDescription: "Key facts were cross-checked against the following primary sources.",
    accessedAt: "Checked",
    effectiveAt: "Effective",
    relatedTitle: "Related guidance",
    backToIndex: "View all insights",
    disclosureTitle: "Drafting and verification",
    aiDisclosure: "AI assisted with drafting and structure. The stated primary sources and key facts were cross-checked; no human reviewer is claimed.",
    humanDisclosure: "This article was written from and cross-checked against official primary sources. A human reviewer is named only when a real review occurred.",
    legalNotice: "This is general information, not legal, labor or administrative advice for an individual case.",
    revisions: "Publication history",
    contactTitle: "Organize your hiring requirements.",
    contactDescription: "Review the roles and stages required for training, matching, visas and settlement.",
    contactCta: "Hiring preparation",
    latestTitle: "Latest insights",
    latestDescription: "Practical explanations of hiring and visa systems based on official sources.",
    latestCta: "View all",
    processLabel: "In this article",
  },
  ja: {
    eyebrow: "INSIGHTS",
    indexTitle: "外国人材の採用に役立つ、根拠のある実務ガイド",
    indexDescription: "在留資格の名称だけでなく、職務、雇用契約、入国、定着支援の順序と公式な確認先を整理します。",
    policyNotice: "制度や基準は変更される場合があります。基準日、更新日、公式情報を確認し、申請前に管轄機関の最新案内をご確認ください。",
    indexSeoTitle: "インサイト | 外国人材採用・在留資格ガイド",
    indexSeoDescription: "外国人材の採用、在留資格、特定技能に関する企業向け実務ガイドです。公式情報と基準日を明記します。",
    emptyTitle: "確認済みの記事を準備しています",
    emptyDescription: "公式情報と施行日を確認した記事のみ掲載します。",
    readArticle: "記事を読む",
    updated: "更新日",
    published: "公開日",
    minutes: "分",
    reviewBadge: "確認中",
    home: "ホーム",
    indexName: "インサイト",
    asOf: "基準日",
    jurisdiction: "管轄",
    author: "執筆",
    reviewer: "確認",
    reviewedAt: "確認日",
    sourcesTitle: "公式情報",
    sourcesDescription: "主要な事実は、以下の一次情報で確認しています。",
    accessedAt: "確認日",
    effectiveAt: "施行日",
    relatedTitle: "あわせて確認する内容",
    backToIndex: "すべてのインサイトを見る",
    disclosureTitle: "執筆・確認情報",
    aiDisclosure: "この記事はAIによる下書き・整理の補助を受け、記載した公式一次情報と主要事実を照合しています。人による確認者は表示していません。",
    humanDisclosure: "この記事は公式一次情報と主要事実を照合して作成しています。実際に確認した場合のみ人による確認者を表示します。",
    legalNotice: "この記事は一般的な情報提供を目的とし、個別案件への法律・労務・行政上の助言ではありません。",
    revisions: "公開・更新履歴",
    contactTitle: "採用要件を一緒に整理しませんか。",
    contactDescription: "教育、マッチング、在留手続、定着まで必要な段階と役割をご案内します。",
    contactCta: "採用準備案内",
    latestTitle: "最新インサイト",
    latestDescription: "公式情報をもとに、採用と在留制度の要点を実務の視点で整理します。",
    latestCta: "すべて見る",
    processLabel: "この記事の確認順序",
  },
  ne: {
    eyebrow: "INSIGHTS",
    indexTitle: "वैदेशिक जनशक्ति भर्तीका लागि प्रमाणमा आधारित व्यावहारिक मार्गदर्शिका",
    indexDescription: "भिसाको नाम मात्र होइन, पद, सम्झौता, प्रवेश र बसोबास सहयोगको क्रम तथा आधिकारिक पुष्टि गर्ने स्थान स्पष्ट गर्छौँ।",
    policyNotice: "प्रणाली र मापदण्ड परिवर्तन हुन सक्छन्। आधार मिति, संशोधन मिति र आधिकारिक स्रोत जाँच्नुहोस् र आवेदनअघि सम्बन्धित निकायको नवीनतम सूचना पुष्टि गर्नुहोस्।",
    indexSeoTitle: "जानकारी | वैदेशिक जनशक्ति भर्ती र भिसा मार्गदर्शिका",
    indexSeoDescription: "वैदेशिक जनशक्ति भर्ती, रोजगारी भिसा र जापानको निर्दिष्ट सीपसम्बन्धी कम्पनीका लागि व्यावहारिक मार्गदर्शिका।",
    emptyTitle: "पुष्टि गरिएका लेख तयार हुँदैछन्",
    emptyDescription: "आधिकारिक स्रोत र लागू मिति जाँचिएका लेख मात्र यहाँ प्रकाशित हुन्छन्।",
    readArticle: "लेख पढ्नुहोस्",
    updated: "संशोधन मिति",
    published: "प्रकाशन मिति",
    minutes: "मिनेट",
    reviewBadge: "समीक्षामा",
    home: "गृहपृष्ठ",
    indexName: "जानकारी",
    asOf: "आधार मिति",
    jurisdiction: "अधिकार क्षेत्र",
    author: "लेखन",
    reviewer: "समीक्षा",
    reviewedAt: "समीक्षा मिति",
    sourcesTitle: "आधिकारिक स्रोत",
    sourcesDescription: "मुख्य तथ्यहरू तलका प्राथमिक स्रोतबाट पुष्टि गरिएका छन्।",
    accessedAt: "पुष्टि मिति",
    effectiveAt: "लागू मिति",
    relatedTitle: "सम्बन्धित जानकारी",
    backToIndex: "सबै जानकारी हेर्नुहोस्",
    disclosureTitle: "लेखन र समीक्षा जानकारी",
    aiDisclosure: "मस्यौदा र संरचनामा AI सहयोग लिइएको छ। उल्लेखित आधिकारिक प्राथमिक स्रोत र मुख्य तथ्य तुलना गरिएका छन्; मानव समीक्षक दाबी गरिएको छैन।",
    humanDisclosure: "लेख आधिकारिक प्राथमिक स्रोतसँग मुख्य तथ्य तुलना गरेर तयार गरिएको हो। वास्तविक समीक्षा भएमा मात्र मानव समीक्षक उल्लेख गरिन्छ।",
    legalNotice: "यो लेख सामान्य जानकारीका लागि हो; व्यक्तिगत विषयमा कानुनी, श्रम वा प्रशासनिक सल्लाह होइन।",
    revisions: "प्रकाशन र संशोधन इतिहास",
    contactTitle: "कम्पनीको भर्ती आवश्यकता सँगै व्यवस्थित गरौँ।",
    contactDescription: "शिक्षा, मिलान, भिसा र बसोबाससम्मका आवश्यक चरण र भूमिका जानकारी दिन्छौँ।",
    contactCta: "भर्ती तयारी जानकारी",
    latestTitle: "नवीनतम जानकारी",
    latestDescription: "आधिकारिक स्रोतका आधारमा भर्ती र भिसा प्रणालीका मुख्य बुँदा व्यावहारिक रूपमा प्रस्तुत गर्छौँ।",
    latestCta: "सबै लेख हेर्नुहोस्",
    processLabel: "यो लेख पढ्ने क्रम",
  },
  vi: {
    eyebrow: "KIẾN THỨC",
    indexTitle: "Hướng dẫn thực tiễn có căn cứ cho tuyển dụng quốc tế",
    indexDescription: "Trình tự về công việc, hợp đồng, nhập cảnh và hỗ trợ ổn định cùng đường dẫn đến cơ quan chính thức.",
    policyNotice: "Quy định có thể thay đổi. Hãy kiểm tra ngày cơ sở, ngày cập nhật và nguồn chính thức trước khi nộp hồ sơ.",
    indexSeoTitle: "Kiến thức | Tuyển dụng lao động nước ngoài và thị thực",
    indexSeoDescription: "Hướng dẫn cho doanh nghiệp về thị thực lao động Hàn Quốc và Kỹ năng đặc định Nhật Bản, kèm nguồn chính thức.",
    emptyTitle: "Đang chuẩn bị bài đã xác minh",
    emptyDescription: "Chỉ đăng bài đã đối chiếu nguồn chính thức.",
    readArticle: "Đọc bài",
    updated: "Cập nhật",
    published: "Đăng",
    minutes: " phút",
    reviewBadge: "Đang rà soát",
    home: "Trang chủ",
    indexName: "Kiến thức",
    asOf: "Cơ sở ngày",
    jurisdiction: "Phạm vi",
    author: "Biên soạn",
    reviewer: "Người rà soát",
    reviewedAt: "Ngày rà soát",
    sourcesTitle: "Nguồn chính thức",
    sourcesDescription: "Các sự kiện chính được đối chiếu với nguồn sơ cấp sau.",
    accessedAt: "Ngày kiểm tra",
    effectiveAt: "Hiệu lực",
    relatedTitle: "Nội dung liên quan",
    backToIndex: "Xem tất cả bài",
    disclosureTitle: "Biên soạn và xác minh",
    aiDisclosure: "AI hỗ trợ bản nháp và cấu trúc. Nguồn sơ cấp và sự kiện chính đã được đối chiếu; không tuyên bố có người rà soát.",
    humanDisclosure: "Bài được soạn và đối chiếu với nguồn sơ cấp chính thức. Chỉ nêu người rà soát khi đã có rà soát thực tế.",
    legalNotice: "Đây là thông tin chung, không phải tư vấn pháp lý, lao động hay hành chính cho trường hợp cụ thể.",
    revisions: "Lịch sử đăng và sửa",
    contactTitle: "Sắp xếp yêu cầu tuyển dụng của doanh nghiệp.",
    contactDescription: "Xem các giai đoạn cần thiết cho đào tạo, kết nối, thị thực và ổn định.",
    contactCta: "Hướng dẫn chuẩn bị tuyển dụng",
    latestTitle: "Bài mới",
    latestDescription: "Giải thích thực tiễn về tuyển dụng và thị thực dựa trên nguồn chính thức.",
    latestCta: "Xem tất cả",
    processLabel: "Nội dung bài",
  },
  lo: {
    eyebrow: "ບົດຄວາມ",
    indexTitle: "ຄູ່ມືປະຕິບັດທີ່ມີແຫຼ່ງອ້າງອີງສຳລັບການຈ້າງສາກົນ",
    indexDescription: "ລຳດັບການກວດວຽກ, ສັນຍາ, ການເຂົ້າປະເທດ ແລະ ການຕັ້ງຖິ່ນຖານ ພ້ອມແຫຼ່ງທາງການ.",
    policyNotice: "ກົດລະບຽບອາດປ່ຽນໄດ້. ກວດວັນທີອ້າງອີງ, ວັນປັບປຸງ ແລະ ແຫຼ່ງທາງການກ່ອນຍື່ນ.",
    indexSeoTitle: "ບົດຄວາມ | ການຈ້າງແຮງງານຕ່າງຊາດແລະວີຊາ",
    indexSeoDescription: "ຄູ່ມືສຳລັບນາຍຈ້າງກ່ຽວກັບວີຊາເກົາຫຼີແລະທັກສະສະເພາະຍີ່ປຸ່ນ ພ້ອມແຫຼ່ງທາງການ.",
    emptyTitle: "ກຳລັງກຽມບົດຄວາມທີ່ກວດສອບແລ້ວ",
    emptyDescription: "ເຜີຍແຜ່ສະເພາະບົດຄວາມທີ່ທຽບກັບແຫຼ່ງທາງການ.",
    readArticle: "ອ່ານບົດຄວາມ",
    updated: "ປັບປຸງ",
    published: "ເຜີຍແຜ່",
    minutes: " ນາທີ",
    reviewBadge: "ກຳລັງກວດ",
    home: "ໜ້າຫຼັກ",
    indexName: "ບົດຄວາມ",
    asOf: "ອ້າງອີງວັນທີ",
    jurisdiction: "ເຂດອຳນາດ",
    author: "ຜູ້ຂຽນ",
    reviewer: "ຜູ້ກວດ",
    reviewedAt: "ວັນກວດ",
    sourcesTitle: "ແຫຼ່ງທາງການ",
    sourcesDescription: "ຂໍ້ເທັດຈິງຫຼັກຖືກທຽບກັບແຫຼ່ງຂັ້ນຕົ້ນຕໍ່ໄປນີ້.",
    accessedAt: "ວັນກວດ",
    effectiveAt: "ມີຜົນ",
    relatedTitle: "ເນື້ອຫາກ່ຽວຂ້ອງ",
    backToIndex: "ເບິ່ງບົດຄວາມທັງໝົດ",
    disclosureTitle: "ການຂຽນແລະກວດສອບ",
    aiDisclosure: "AI ຊ່ວຍຮ່າງແລະຈັດໂຄງສ້າງ. ໄດ້ທຽບແຫຼ່ງຂັ້ນຕົ້ນແລະຂໍ້ເທັດຈິງ; ບໍ່ໄດ້ອ້າງຜູ້ກວດທີ່ເປັນຄົນ.",
    humanDisclosure: "ບົດຄວາມຖືກຂຽນແລະທຽບກັບແຫຼ່ງທາງການ. ຈະລະບຸຜູ້ກວດເມື່ອມີການກວດຈິງເທົ່ານັ້ນ.",
    legalNotice: "ນີ້ແມ່ນຂໍ້ມູນທົ່ວໄປ ບໍ່ແມ່ນຄຳປຶກສາກົດໝາຍ, ແຮງງານ ຫຼື ບໍລິຫານສຳລັບກໍລະນີສະເພາະ.",
    revisions: "ປະຫວັດເຜີຍແຜ່",
    contactTitle: "ຈັດລະບຽບຄວາມຕ້ອງການຮັບສະໝັກ.",
    contactDescription: "ກວດຂັ້ນຕອນສຳລັບການຝຶກ, ຈັບຄູ່, ວີຊາ ແລະ ຕັ້ງຖິ່ນຖານ.",
    contactCta: "ຄູ່ມືກຽມການຈ້າງ",
    latestTitle: "ບົດຄວາມລ່າສຸດ",
    latestDescription: "ອະທິບາຍການຈ້າງແລະວີຊາຈາກແຫຼ່ງທາງການ.",
    latestCta: "ເບິ່ງທັງໝົດ",
    processLabel: "ເນື້ອຫາບົດ",
  },
};

export function formatBlogDate(locale: BlogLocale, date: string): string {
  const languageTag = { ko: "ko-KR", en: "en-US", ja: "ja-JP", ne: "ne-NP", vi: "vi-VN", lo: "lo-LA" }[locale];
  return new Intl.DateTimeFormat(languageTag, { year: "numeric", month: "long", day: "numeric" }).format(
    new Date(`${date}T00:00:00+09:00`),
  );
}
